# Generated by Django 4.0.2 on 2022-02-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('player_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('xp', models.BigIntegerField(default=0)),
                ('gold', models.BigIntegerField(default=0)),
            ],
        ),
    ]
